export const ROUTES = {
  LOGIN: "Login",
  ONBOARDING: "Onboarding",
  SIGNUP: "Signup",
  VerifyEmail: "VerifyEmail",
  PersonalInfo: "PersonalInfo",
  ChooseYourPlan: "ChooseYourPlan",
  PaymentDetails: "PaymentDetails",
  LinkYourBank: "LinkYourBank",
  YoureAllSet: "YoureAllSet",
  HOME: "Home",
  Settings: "Settings",
  ForgotPassword: "ForgotPassword",
  ResetPassword: "ResetPassword",
  Notifications: "Notifications",
};
